"""create jobs table

Revision ID: 325e0a172631
Revises: d40bea206908
Create Date: 2026-09-26 20:58:38.213834

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "325e0a172631"
down_revision: Union[str, Sequence[str], None] = "d40bea206908"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

job_status_enum = postgresql.ENUM(
    "PENDING",
    "PROCESSING",
    "SUCCESS",
    "PARTIAL_SUCCESS",
    "FAILED",
    name="job_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    job_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "jobs",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("status", job_status_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jobs")
    job_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
