"""create requests table

Revision ID: d40bea206908
Revises:
Create Date: 2026-09-19 19:31:52.588989

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d40bea206908"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

request_status_enum = postgresql.ENUM(
    "NEW",
    "VALIDATION_FAILED",
    "QUEUED",
    "PROCESSING",
    "APPROVED",
    "REJECTED",
    "MANUAL_REVIEW",
    "FAILED",
    name="request_status",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    request_status_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "requests",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("external_request_id", sa.String(length=100), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("product_type", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", request_status_enum, nullable=False),
        sa.PrimaryKeyConstraint("request_id"),
        sa.UniqueConstraint("external_request_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("requests")
    request_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
